### ISSUE TITLE
Request: Ability to set other scrollbar related vendor specific psuedo-classes.

### ISSUE THREAD

**Issue by erlandsona** [lukewarlow/tailwind-scrollbar-utilities#5]
![image](https://github.com/user-attachments/assets/bcd13cb5-3383-4903-9699-4069dea10b6e)

**Comment by lukewarlow** [comment]
This plugin intentionally doesn't support the vendor prefixing. We have the standards properties which have been improving in browser support in recent times.

**Comment by erlandsona** [comment]
Fair enough, just figured I'd ask :+1:
